RABBITMQ_USERNAME = "sdfsdfsd"
RABBITMQ_PASSWORD = "safddsf"
RABBITMQ_HOST = "localhost"
RABBITMQ_PORT = 5672
RABBIT_QUEUE_NAME = "ams"
RABBIT_EXCHANGE_NAME = "ams"
RABBIT_ROUTING_KEY = "ams"

RABBIT_QUEUE_MAX_SIZE = 400


MONGODB_URL ="asdflocalefdsfdsfhos"
DATABASE_NAME = "mydatabase"